
export const actionTypes = {
    //hone screen typler
    FETCH_TRENDING_ALL:"FETCH_TRENDING_ALL",
    FETCH_NOW_PLAYING: "FETCH_NOW_PLAYING",
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_UPCOMING :"FETCH_UPCOMING ",
    FETCH_POPULAR :"FETCH_POPULAR",
    FETCH_TOP_RATED: "FETCH_TOP_RATED:",

    //category screen type
    FETCH_GENRES: "FETCH_GENRES",
    FETCH_GENRE_MOVIES: "FETCH_GENRE_MOVIES",

    //Detail screen
    FETCH_DETAIL_MOVIES: " FETCH_DETAIL_MOVIES",
    FETCH_SIMILAR_MOVIES:"FETCH_SIMILAR_MOVIES",
    FETCH_CAST_MOVIES:"FETCH_CAST_MOVIES",
    FETCH_POSTER_MOVIES:"FETCH_POSTER_MOVIES", 
    FETCH_REVIEWS_MOVIES:"FETCH_REVIEWS_MOVIES",
    //search screen
    FETCH_SEARCH_MOVIES: "  FETCH_SEARCH_MOVIES",
    //fragman
    FETCH_FRAGMAN_MOVIE:" FETCH_FRAGMAN_MOVIE",
    //user detail
    FETCH_PERSON_DETAIL : "FETCH_PERSON_DETAIL",
    FETCH_PERSON_DETAIL_MOVIES:" FETCH_PERSON_DETAIL_MOVIES",

    //favorite screen
    ADD_FAVORITE_LIST:"ADD_FAVORITE_LIST",
    REMOVE_FAVORITE_LIST:"REMOVE_FAVORITE_LIST",
    //watching screen
    ADD_WATCH_LIST:"ADD_WATCH_LIST",
    REMOVE_WATCH_LIST:"REMOVE_WATCH_LIST",
}